apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd
spec:
  replicas: 3
  selector:
    app: httpd
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: swashikan/container_automation:contai
        ports:
        - containerPort: 80
